### ISSUE TITLE
npm run strat 失败

### ISSUE THREAD

**Issue by abchbx** [zjrwtx/SFT-data-builder#10]
(base) root@intern-studio-50139351:~/SFT-data-builder# npm run start

> reacttemplate@0.1.0 start /root/SFT-data-builder
> react-scripts start

/root/SFT-data-builder/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/SFT-data-builder/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reacttemplate@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reacttemplate@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-11-27T04_13_23_025Z-debug.log

**Comment by zjrwtx** [comment]
你好 请问执行npm install 依赖了吗

**Comment by abchbx** [comment]
执行了啊

**Comment by abchbx** [comment]
> 你好 请问执行npm install 依赖了吗

(base) root@intern-studio-50139351:~/SFT-data-builder# npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 10.075s

270 packages are looking for funding
  run `npm fund` for details
